### ISSUE TITLE
PDF page 20 is missing equiv operator

### ISSUE THREAD

**Issue by robconery** [bigmachine-io/imposter-v2#7]
From Twitter:
https://twitter.com/RosaCtrl/status/1100470198941954049/photo/1

**Comment by robconery** [comment]
This is for @robconery

**Comment by tssm** [comment]
Other issues that I have found that may or may not be related:

- Page 5: "it’s the former.As it turns out, Clarke's Third Law" (missing space before "As")
- Page 7: there's a weird "v" at the end
- Page 11: same
- Page 16: first line in the snippet has an smaller font
- Page 19: "just like the standard OR (, recall)" (missing symbol before the coma?)
- Page 20: "The operator is a stacked equality sign: ." (missing sign)
- Page 20: "An XOR is defined as an OR statement ()"
- Page 20: "We can string together Boolean operations to achieve this: ." (missing symbol?)
- Page 23: "Binary is an encoding for information represented by the symbols ." (missing symbols)
- Page 42: "The only place it falls apart is with the statement (two trues are true)" (better to use quotes?)

**Comment by robconery** [comment]
Wanted to touch base on this again - I've changed my platform around and am polishing the next release which deals with this problem. I should have it ready within a few weeks.

**Comment by tssm** [comment]
Hey @robconery, any news on this? I really want to read the book, but in its current state is impossible, and because the source is not public I cannot figure out how to fix it :(

**Comment by robconery** [comment]
Yep! I'll send you an email...
GitHub <notifications@github.com> wrote:
“Hey @robconery, any news on this? I really want to read the book, but in its current state is impossible, and because the source is not public I cannot figure out how to fix it :(”

**Comment by robconery** [comment]
Would you mind pinging me at rob at bigmachine.io? I have a preview link here for the PDF (I need to update the epub/kindle bits) that I can send along to you.

**Comment by tssm** [comment]
Done, thanks!
